import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import PageTransitionWrapper from "./components/Home/PageTransitionWrapper";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body className={`${inter.variable} antialiased bg-white interFont`}>
        <Navbar />
        <PageTransitionWrapper>
          <main className="pt-12">{children}</main>
        </PageTransitionWrapper>
        <Footer />
      </body>
    </html>
  );
}
